import { FormEvent, useEffect, useRef, useState } from 'react';
import { homeApi } from './api/home.api-service';
import { DateItem, RequestedWindow } from './api/home.model';
import { homeService } from './page.service';
import { useRxBind } from '../../common/utils/use-rx-bind';
import { isSameVapidPublicKey, vapidPublicKeyToBytes } from '../../common/utils/vapid';

const readable=(value:string|null,eventDate?:string|null,isAllDay?:boolean)=>isAllDay&&eventDate?new Intl.DateTimeFormat('ru-RU',{dateStyle:'long'}).format(new Date(`${eventDate}T00:00:00`)):value?new Intl.DateTimeFormat('ru-RU',{dateStyle:'long',timeStyle:'short'}).format(new Date(value)):'Когда решите вместе';
const requestedWindowLabels:Record<RequestedWindow,string>={today:'Сегодня',this_week:'На этой неделе',this_month:'В этом месяце',next_month:'В следующем месяце',idea:'Это просто идея'};
const plannedWindows:RequestedWindow[]=['today','this_week','this_month','next_month'];
const dateTiming=(item:DateItem)=>item.startsAt||item.eventDate?readable(item.startsAt,item.eventDate,item.isAllDay):item.requestedWindow?requestedWindowLabels[item.requestedWindow]:readable(item.startsAt,item.eventDate,item.isAllDay);
const planDeadline=(item:DateItem)=>{if(item.startsAt)return new Date(item.startsAt).valueOf();const now=new Date();const endOfDay=(date:Date)=>new Date(date.getFullYear(),date.getMonth(),date.getDate(),23,59,59,999).valueOf();if(item.eventDate)return endOfDay(new Date(`${item.eventDate}T00:00:00`));if(item.requestedWindow==='today')return endOfDay(now);if(item.requestedWindow==='this_week'){const end=new Date(now);end.setDate(now.getDate()+((7-now.getDay())%7));return endOfDay(end);}if(item.requestedWindow==='this_month')return new Date(now.getFullYear(),now.getMonth()+1,0,23,59,59,999).valueOf();if(item.requestedWindow==='next_month')return new Date(now.getFullYear(),now.getMonth()+2,0,23,59,59,999).valueOf();return Number.MAX_SAFE_INTEGER;};
type InstallPromptEvent = Event & { prompt:()=>Promise<void>; userChoice:Promise<{outcome:string}> };
function Auth() {
  const [mode,setMode]=useState<'login'|'register'>('login'); const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [spaceName,setSpaceName]=useState('Мы вдвоём'); const [busy,setBusy]=useState(false); const error=useRxBind(homeService.error$);
  const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);homeService.error$.next(null);try{if(mode==='register')await homeService.register({name,email,password,spaceName});else await homeService.login({email,password});}catch(error){homeService.error$.next(error instanceof Error?error.message:'Не удалось войти');}finally{setBusy(false);}};
  return <main className="onboarding"><section className="welcome-card"><div className="mark">♥</div><p className="eyebrow">DATE, NOT HATE</p><h1>{mode==='login'?'С возвращением.':'Больше близости. Меньше «ты опять забыл».'}</h1><p className="lead">Планируйте время вдвоём бережно.</p><div className="auth-tabs"><button className={mode==='login'?'active':''} type="button" onClick={()=>setMode('login')}>Войти</button><button className={mode==='register'?'active':''} type="button" onClick={()=>setMode('register')}>Регистрация</button></div><form onSubmit={submit}>{mode==='register'&&<><label>Твоё имя<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Название пространства<input required value={spaceName} onChange={e=>setSpaceName(e.target.value)}/></label></>}<label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Пароль<input required minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Минимум 8 символов"/></label>{error&&<p className="error">{error}</p>}<button disabled={busy}>{busy?'Подождите…':mode==='login'?'Войти в пространство':'Создать пространство'}</button></form>{mode==='login'&&<a className="forgot-link" href="?forgot=1">Не помню пароль</a>}</section></main>;
}

function PasswordReset({token}:{token?:string}) {
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [repeat,setRepeat]=useState(''); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
  const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);try{if(token){if(password!==repeat)throw new Error('Пароли не совпадают.');await homeApi.confirmPasswordReset(token,password);setMessage('Пароль изменён. Теперь можно войти.');history.replaceState({},'',location.pathname);}else{await homeApi.requestPasswordReset(email);setMessage('Если профиль существует, ссылка уже отправлена. Проверьте почту.');}}catch(error){setMessage(error instanceof Error?error.message:'Не удалось восстановить пароль.');}finally{setBusy(false);}};
  return <main className="onboarding"><section className="welcome-card"><div className="mark">♥</div><p className="eyebrow">ВОССТАНОВЛЕНИЕ ПАРОЛЯ</p><h1>{token?'Задайте новый пароль':'Вернём доступ'}</h1><p className="lead">{token?'Ссылка действует 30 минут и используется один раз.':'Укажем путь к восстановлению без раскрытия существования профиля.'}</p><form onSubmit={submit}>{!token?<label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label>:<><label>Новый пароль<input required minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><label>Повторите пароль<input required minLength={8} type="password" value={repeat} onChange={e=>setRepeat(e.target.value)}/></label></>}{message&&<p className="reset-message">{message}</p>}<button disabled={busy}>{busy?'Подождите…':token?'Сохранить пароль':'Отправить magic-link'}</button></form><a className="forgot-link" href="/">Вернуться ко входу</a></section></main>;
}

function EmailVerification({token}:{token:string}) {
  const [message,setMessage]=useState('Подтверждаем email…');
  useEffect(()=>{void homeApi.confirmEmailVerification(token).then(session=>{localStorage.setItem('dnh-session',JSON.stringify(session));location.replace('/');}).catch(error=>setMessage(error instanceof Error?error.message:'Не удалось подтвердить email.'));},[token]);
  return <main className="onboarding"><section className="welcome-card"><div className="mark">♥</div><p className="eyebrow">ПОДТВЕРЖДЕНИЕ EMAIL</p><h1>{message}</h1></section></main>;
}

function AcceptInvite({invite}:{invite:string}) {
  const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [busy,setBusy]=useState(false); const error=useRxBind(homeService.error$);
  const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);try{await homeService.acceptInvite(invite,{name,email,password});history.replaceState({},'',location.pathname);}catch(error){homeService.error$.next(error instanceof Error?error.message:'Не удалось присоединиться');}finally{setBusy(false);}};
  return <main className="onboarding"><section className="welcome-card"><div className="mark">♥</div><p className="eyebrow">ВАС ЖДУТ</p><h1>Вас пригласили в пространство для свиданий.</h1><form onSubmit={submit}><label>Ваше имя<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Email<input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Пароль<input required minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p className="error">{error}</p>}<button disabled={busy}>{busy?'Присоединяем…':'Присоединиться'}</button></form></section></main>;
}

function CreateDate({close}:{close:()=>void}) {
  const space=useRxBind(homeService.space$); const types=space?.dateTypes.filter(type=>type.enabled)??[]; const [typeId,setTypeId]=useState(''); const [title,setTitle]=useState(''); const [eventDate,setEventDate]=useState(''); const [eventTime,setEventTime]=useState(''); const [organizerMode,setOrganizerMode]=useState<'self'|'partner'>('self'); const [requestedWindow,setRequestedWindow]=useState<RequestedWindow|''>(''); const [idea,setIdea]=useState(false); const [selfTiming,setSelfTiming]=useState<'exact'|'window'>('exact'); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  useEffect(()=>{const dismiss=(event:MouseEvent)=>{const overlays=document.querySelectorAll('.overlay');if(overlays[overlays.length-1]===event.target)close();};document.addEventListener('click',dismiss);return()=>document.removeEventListener('click',dismiss);},[close]);
  const hints:Record<string,string[]>={'Ужин вне дома':['Выберите новое место рядом с домом','Забронируйте столик и не раскрывайте детали'],'Кино или театр':['Выберите сеанс, который заканчивается не слишком поздно','Добавьте короткую прогулку после'],'Прогулка':['Возьмите кофе с собой','Выберите маршрут с одной новой точкой'],'Игра вдвоём':['Подготовьте лёгкий перекус','Договоритесь не смотреть в телефоны'],'Домашний киносеанс':['Пусть фильм выберет партнёр','Подготовьте плед и любимую еду'],'Новое впечатление':['Выберите одно новое занятие','Оставьте время спокойно обсудить впечатления']};
  useEffect(()=>{if(!typeId&&types[0]){setTypeId(types[0].id);setTitle(types[0].title);}},[typeId,types]);
  useEffect(()=>{if(idea||organizerMode==='partner'||selfTiming==='window'){setEventDate('');setEventTime('');}},[idea,organizerMode,selfTiming]);
  const submit=async(event:FormEvent)=>{event.preventDefault();if(busy)return;const exact=!idea&&organizerMode==='self'&&selfTiming==='exact';setBusy(true);setError('');try{await homeService.createDate({typeId,title,eventDate:null,startsAt:exact?new Date(`${eventDate}T${eventTime}:00`).toISOString():null,isAllDay:false,organizerMode,requestedWindow:idea?'idea':exact?null:requestedWindow});close();}catch(cause){setError(cause instanceof Error?cause.message:'Не удалось создать свидание.');}finally{setBusy(false);}};
  const selected=types.find(type=>type.id===typeId);
  const needsTiming=!idea&&(organizerMode==='partner'||selfTiming==='window')&&!requestedWindow;
  return <div className="overlay"><form className="modal" onSubmit={submit}><button className="close" type="button" onClick={close}>×</button><p className="eyebrow">НОВЫЙ ПОВОД</p><h2>Позвать на свидание</h2><label>Что хочется?<select value={typeId} onChange={e=>{setTypeId(e.target.value);setTitle(types.find(type=>type.id===e.target.value)?.title??'');}}>{types.map(type=><option key={type.id} value={type.id}>{type.emoji} {type.title}</option>)}</select></label>{selected&&hints[selected.title]&&<div className="idea-hints"><b>Идея для старта</b>{hints[selected.title].map(hint=><span key={hint}>• {hint}</span>)}</div>}<label>Можно назвать по-своему<input required value={title} onChange={e=>setTitle(e.target.value)}/></label><button aria-label="Это просто идея" className={'idea-option '+(idea?'selected':'')} type="button" onClick={()=>setIdea(value=>!value)}><b>Это просто идея</b><span>Сохраним в Банке идей без срока и организатора</span></button>{!idea&&<><fieldset><legend>Кто организует?</legend><label className={'choice '+(organizerMode==='self'?'selected':'')}><input type="radio" checked={organizerMode==='self'} onChange={()=>{setOrganizerMode('self');setRequestedWindow('');}}/><b>Я</b><span>Сделаю сюрприз и всё подготовлю</span></label><label className={'choice '+(organizerMode==='partner'?'selected':'')}><input type="radio" checked={organizerMode==='partner'} onChange={()=>{setOrganizerMode('partner');setEventDate('');setEventTime('');}}/><b>Партнёр</b><span>Хочу получить приглашение и довериться</span></label></fieldset>{organizerMode==='self'?<fieldset><legend>Когда?</legend><div className="timing-options"><button className={selfTiming==='exact'?'selected':''} type="button" onClick={()=>setSelfTiming('exact')}>Точная дата и время</button><button className={selfTiming==='window'?'selected':''} type="button" onClick={()=>setSelfTiming('window')}>Выбрать период</button></div>{selfTiming==='exact'?<div className="date-time-fields"><label>Дата<input required type="date" value={eventDate} onChange={e=>setEventDate(e.target.value)}/></label><label>Время<input required type="time" value={eventTime} onChange={e=>setEventTime(e.target.value)}/></label></div>:<div className="window-options">{plannedWindows.map(window=><button className={requestedWindow===window?'selected':''} type="button" key={window} onClick={()=>setRequestedWindow(window)}>{requestedWindowLabels[window]}</button>)}</div>}</fieldset>:<fieldset><legend>Когда хотелось бы?</legend><div className="window-options">{plannedWindows.map(window=><button className={requestedWindow===window?'selected':''} type="button" key={window} onClick={()=>setRequestedWindow(window)}>{requestedWindowLabels[window]}</button>)}</div></fieldset>}</>}{error&&<p className="error">{error}</p>}<button disabled={needsTiming||busy}>{busy?'Создаём…':'Отправить приглашение'}</button></form></div>;
}

function ClaimIdeaDialog({item,close}:{item:DateItem;close:()=>void}) {
  const [timing,setTiming]=useState<'exact'|'window'>('window'); const [eventDate,setEventDate]=useState(''); const [eventTime,setEventTime]=useState(''); const [requestedWindow,setRequestedWindow]=useState<RequestedWindow|''>(''); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  useEffect(()=>{const dismiss=(event:MouseEvent)=>{const overlays=document.querySelectorAll('.overlay');if(overlays[overlays.length-1]===event.target)close();};document.addEventListener('click',dismiss);return()=>document.removeEventListener('click',dismiss);},[close]);
  const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setError('');try{await homeService.claimIdea(item.id,{startsAt:timing==='exact'?new Date(`${eventDate}T${eventTime}:00`).toISOString():null,requestedWindow:timing==='window'?requestedWindow:null});close();}catch(cause){setError(cause instanceof Error?cause.message:'Не удалось взять идею в работу.');}finally{setBusy(false);}};
  const invalid=timing==='exact'?(!eventDate||!eventTime):!requestedWindow;
  return <div className="overlay"><form className="modal" onSubmit={submit}><button className="close" type="button" onClick={close}>×</button><p className="eyebrow">БАНК ИДЕЙ</p><h2>Организовать свидание</h2><p className="lead">{item.emoji} {item.title}</p><fieldset><legend>Когда?</legend><div className="timing-options"><button className={timing==='exact'?'selected':''} type="button" onClick={()=>setTiming('exact')}>Точная дата и время</button><button className={timing==='window'?'selected':''} type="button" onClick={()=>setTiming('window')}>Выбрать период</button></div>{timing==='exact'?<div className="date-time-fields"><label>Дата<input required type="date" value={eventDate} onChange={event=>setEventDate(event.target.value)}/></label><label>Время<input required type="time" value={eventTime} onChange={event=>setEventTime(event.target.value)}/></label></div>:<div className="window-options">{plannedWindows.map(window=><button className={requestedWindow===window?'selected':''} type="button" key={window} onClick={()=>setRequestedWindow(window)}>{requestedWindowLabels[window]}</button>)}</div>}</fieldset>{error&&<p className="error">{error}</p>}<button disabled={busy||invalid}>{busy?'Сохраняем…':'Взять в работу'}</button></form></div>;
}

const localDateTime=(value:string|null)=>{if(!value)return {date:'',time:''};const date=new Date(value);const pad=(part:number)=>String(part).padStart(2,'0');return {date:`${date.getFullYear()}-${pad(date.getMonth()+1)}-${pad(date.getDate())}`,time:`${pad(date.getHours())}:${pad(date.getMinutes())}`};};

function PhotoPreview({filename,close}:{filename:string;close:()=>void}) {
  return <div className="overlay photo-lightbox" onClick={close}><section className="photo-lightbox__content" role="dialog" aria-modal="true" aria-label="Просмотр фотографии" onClick={event=>event.stopPropagation()}><button className="close" type="button" aria-label="Закрыть просмотр" onClick={close}>×</button><img src={'/photos/'+filename} alt="Воспоминание со свидания"/><a className="complete" href={'/photos/'+filename} download>Скачать фото</a></section></div>;
}

function DateDetailsDialog({item,close}:{item:DateItem;close:()=>void}) {
  const session=useRxBind(homeService.session$)!; const initial=localDateTime(item.startsAt); const [eventDate,setEventDate]=useState(initial.date||item.eventDate||''); const [eventTime,setEventTime]=useState(initial.time); const [comment,setComment]=useState(item.organizerComment??''); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [uploading,setUploading]=useState(false); const [previewFilename,setPreviewFilename]=useState<string|null>(null); const photoInput=useRef<HTMLInputElement>(null);
  useEffect(()=>{const dismiss=(event:MouseEvent)=>{const overlays=document.querySelectorAll('.overlay');if(overlays[overlays.length-1]===event.target)close();};document.addEventListener('click',dismiss);return()=>document.removeEventListener('click',dismiss);},[close]);
  const isOrganiser=item.organizerMode==='self'?item.createdBy===session.user.id:item.createdBy!==session.user.id;
  const submit=async(event:FormEvent)=>{event.preventDefault();if(!eventDate||!eventTime||!comment.trim())return;setBusy(true);setError('');try{await homeService.sendOrganizerComment(item.id,{startsAt:new Date(`${eventDate}T${eventTime}:00`).toISOString(),comment:comment.trim()});close();}catch(cause){setError(cause instanceof Error?cause.message:'Не удалось отправить детали.');}finally{setBusy(false);}}; const upload=async(files:FileList|null)=>{if(!files)return;setUploading(true);try{await homeApi.upload(item.id,session.token,Array.from(files));await homeService.refresh();}finally{setUploading(false);}};
  return <><div className="overlay"><section className="modal date-details" role="dialog" aria-modal="true" aria-label="Детали свидания"><button className="close" type="button" aria-label="Закрыть детали" onClick={close}>×</button><p className="eyebrow">ДЕТАЛИ СВИДАНИЯ</p><div className="date-details__heading"><span>{item.emoji}</span><div><p>{item.typeTitle}</p><h2>{item.title}</h2></div></div><div className="date-details__meta"><div><b>Когда</b><span>{item.startsAt||item.eventDate||item.requestedWindow?dateTiming(item):'Точное время ещё не назначено'}</span></div><div><b>Комментарий</b><span>{item.organizerComment??'Комментарий пока не добавлен'}</span></div></div>{item.status==='completed'&&<div className="date-details__photos"><b>Фотографии</b>{item.photos.length>0&&<div className="photos">{item.photos.map(photo=><button key={photo.id} className="photo-preview-trigger" type="button" aria-label={'Открыть фото: '+photo.filename} onClick={()=>setPreviewFilename(photo.filename)}><img src={'/photos/'+photo.filename} alt="Воспоминание со свидания"/></button>)}</div>}{item.photos.length<3&&<><input ref={photoInput} hidden type="file" accept="image/*" multiple onChange={event=>void upload(event.target.files)}/><button className="complete" type="button" onClick={()=>photoInput.current?.click()}>{uploading?'Загружаем…':'Добавить фото'}</button></>}</div>}{isOrganiser&&item.status==='planned'?<form className="organizer-comment" onSubmit={submit}><h3>{item.startsAt?'Обновить детали':'Назначить точное время'}</h3><div className="date-time-fields"><label>Дата<input required type="date" value={eventDate} onChange={event=>setEventDate(event.target.value)}/></label><label>Время<input required type="time" value={eventTime} onChange={event=>setEventTime(event.target.value)}/></label></div><label>Комментарий для партнёра<textarea required value={comment} maxLength={1000} onChange={event=>setComment(event.target.value)} placeholder="Например: оденься потеплее, возьми удобную обувь…"/></label>{error&&<p className="error">{error}</p>}<button disabled={busy||!eventDate||!eventTime||!comment.trim()}>{busy?'Отправляем…':'Отправить детали'}</button></form>:item.status==='planned'?<p className="date-details__waiting">Как только организатор назначит время и добавит детали, они появятся здесь.</p>:null}</section></div>{previewFilename&&<PhotoPreview filename={previewFilename} close={()=>setPreviewFilename(null)}/>}</>;
}

function DateCard({item,history,idea,openDetails,organiseIdea}:{item:DateItem;history?:boolean;idea?:boolean;openDetails?:(dateId:string)=>void;organiseIdea?:(item:DateItem)=>void}) {
  const session=useRxBind(homeService.session$)!; const [uploading,setUploading]=useState(false); const [previewFilename,setPreviewFilename]=useState<string|null>(null); const photoInput=useRef<HTMLInputElement>(null); const upload=async(files:FileList|null)=>{if(!files)return;setUploading(true);try{await homeApi.upload(item.id,session.token,Array.from(files));await homeService.refresh();}finally{setUploading(false);}}; const downloadCalendar=async()=>{const calendar=await homeApi.downloadCalendar(item.id,session.token);const url=URL.createObjectURL(calendar);const link=document.createElement('a');link.href=url;link.download='date-not-hate.ics';link.click();URL.revokeObjectURL(url);};
  const details=<><p className="date-type">{item.typeTitle}</p><h3>{item.title}</h3><p className="date-time">{dateTiming(item)}</p></>;
  return <><article className="date-card"><button className="date-emoji date-open" type="button" aria-label={`Открыть детали: ${item.title}, эмодзи`} onClick={()=>openDetails?.(item.id)}>{item.emoji}</button>{history?<div className="date-main"><button className="date-summary date-open" type="button" aria-label={`Открыть детали: ${item.title}`} onClick={()=>openDetails?.(item.id)}>{details}</button><div className="photos">{item.photos.map(photo=><button key={photo.id} className="photo-preview-trigger" type="button" aria-label={'Открыть фото: '+photo.filename} onClick={()=>setPreviewFilename(photo.filename)}><img src={'/photos/'+photo.filename} alt="Воспоминание со свидания"/></button>)}</div></div>:<button className="date-main date-open" type="button" aria-label={`Открыть детали: ${item.title}`} onClick={()=>openDetails?.(item.id)}>{details}</button>}<div className="date-actions">{history&&item.photos.length<3&&<><input ref={photoInput} hidden type="file" accept="image/*" multiple onChange={e=>upload(e.target.files)}/><button className="complete" type="button" onClick={()=>photoInput.current?.click()}>{uploading?'Загружаем…':'Добавить фото'}</button></>}{idea&&<button className="complete" type="button" onClick={()=>organiseIdea?.(item)}>Организовать</button>}{!history&&!idea&&(item.startsAt||item.eventDate)&&<button className="complete" title="Добавить в календарь" onClick={()=>void downloadCalendar()}>＋</button>}{!history&&!idea&&<button className="complete" onClick={()=>homeService.complete(item.id)}>Были</button>}</div></article>{previewFilename&&<PhotoPreview filename={previewFilename} close={()=>setPreviewFilename(null)}/>}</>;
}

function Notifications({openDate}:{openDate:(dateId:string)=>void}) {
  const notices=useRxBind(homeService.notifications$); const [open,setOpen]=useState(false); const unread=notices.filter(item=>!item.readAt).length;
  const read=async(id:string,dateId:string|null)=>{await homeService.readNotification(id);setOpen(false);if(dateId)openDate(dateId);};
  return <div className="notice-wrap"><button className="bell" type="button" aria-label="Уведомления" onClick={()=>setOpen(!open)}><svg aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9"/><path d="M10 21h4"/></svg>{unread>0&&<i>{unread}</i>}</button>{open&&<div className="notice-popover"><b>Уведомления</b>{notices.length===0?<p>Пока ничего нового</p>:notices.map(item=><button className={!item.readAt?'unread':''} key={item.id} onClick={()=>void read(item.id,item.dateId)}><span>{item.body}</span><small>{new Intl.DateTimeFormat('ru-RU',{dateStyle:'short',timeStyle:'short'}).format(new Date(item.createdAt))}</small></button>)}</div>}</div>;
}

function ProfileMenu({name,email}:{name:string;email:string}) {
  const [open,setOpen]=useState(false); const menuRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{const closeMenu=(event:MouseEvent)=>{if(!menuRef.current?.contains(event.target as Node))setOpen(false);}; if(open)document.addEventListener('mousedown',closeMenu); return()=>document.removeEventListener('mousedown',closeMenu);},[open]);
  return <div className="profile-wrap" ref={menuRef}><button className="avatar" type="button" title="Профиль" aria-haspopup="menu" aria-expanded={open} onClick={()=>setOpen(value=>!value)}>{name.slice(0,1).toUpperCase()}</button>{open&&<div className="profile-popover"><div className="profile-summary"><b>{name}</b><small>{email}</small></div><button type="button" onClick={()=>homeService.logout()}>Выйти</button></div>}</div>;
}

function InvitePartner() {
  const [email,setEmail]=useState(''); const [role,setRole]=useState<'member'|'admin'>('member'); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
  const submit=async(event:FormEvent)=>{event.preventDefault();setBusy(true);setMessage('Отправляем приглашение…');try{await homeService.sendInvite(email,role);setMessage('Приглашение отправлено. Проверьте почту партнёра.');setEmail('');}catch(error){setMessage(error instanceof Error?error.message:'Не удалось отправить приглашение.');}finally{setBusy(false);}};
  return <div className="settings-card"><h3>Пригласить партнёра</h3><p>Ссылка придёт на указанный email. Роль выбираете вы, а не приглашённый.</p><form className="invite-form" onSubmit={submit}><input required disabled={busy} type="email" value={email} onChange={event=>setEmail(event.target.value)} placeholder="partner@example.com"/><select disabled={busy} value={role} onChange={event=>setRole(event.target.value as 'member'|'admin')}><option value="member">Участник</option><option value="admin">Администратор</option></select><button disabled={busy}>{busy?'Отправляем…':'Пригласить'}</button></form>{message&&<p className="reset-message">{message}</p>}</div>;
}

function InstallApp() {
  const [prompt,setPrompt]=useState<InstallPromptEvent|null>(null); const standalone=window.matchMedia('(display-mode: standalone)').matches||(navigator as Navigator & {standalone?:boolean}).standalone===true; const ios=/iPad|iPhone|iPod/.test(navigator.userAgent);
  useEffect(()=>{const handler=(event:Event)=>{event.preventDefault();setPrompt(event as InstallPromptEvent);};window.addEventListener('beforeinstallprompt',handler);return()=>window.removeEventListener('beforeinstallprompt',handler);},[]);
  if(standalone)return <div className="settings-card"><h3>Приложение установлено</h3><p>Date, not Hate открывается как отдельное приложение.</p></div>;
  const install=async()=>{if(!prompt)return;await prompt.prompt();setPrompt(null);};
  return <div className="settings-card"><h3>Установить приложение</h3><p>{ios?'Откройте сайт в Safari, нажмите «Поделиться» и выберите «На экран Домой».':'Установите приложение, чтобы оно открывалось с главного экрана.'}</p>{prompt&&<button className="soft-button" onClick={install}>Установить</button>}</div>;
}

function PushSettings() {
  const session=useRxBind(homeService.session$)!; const [configured,setConfigured]=useState<boolean|null>(null); const [publicKey,setPublicKey]=useState<string>(); const [subscribed,setSubscribed]=useState(false); const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
  const supported=window.isSecureContext&&'serviceWorker' in navigator&&'PushManager' in window&&'Notification' in window;
  useEffect(()=>{let active=true;void (async()=>{try{const config=await homeService.pushConfig();const subscription=supported?await (await navigator.serviceWorker.ready).pushManager.getSubscription():null;const subscriptionMatches=Boolean(subscription&&config.publicKey&&isSameVapidPublicKey(subscription.options.applicationServerKey,vapidPublicKeyToBytes(config.publicKey)));if(active){setConfigured(config.enabled);setPublicKey(config.publicKey);setSubscribed(subscriptionMatches);}}catch(error){if(active)setMessage(error instanceof Error?error.message:'Не удалось проверить настройки уведомлений.');}})();return()=>{active=false;};},[session.token,supported]);
  const enable=async()=>{if(!supported){setMessage('Push работает только по HTTPS в установленном приложении.');return;}if(!configured||!publicKey){setMessage('Серверу нужны VAPID-ключи. Инструкция есть в README.');return;}setBusy(true);setMessage('');try{if(await Notification.requestPermission()!=='granted')throw new Error('Разрешение на уведомления не выдано.');const registration=await navigator.serviceWorker.ready;const applicationServerKey=vapidPublicKeyToBytes(publicKey);const currentSubscription=await registration.pushManager.getSubscription();if(currentSubscription&&!isSameVapidPublicKey(currentSubscription.options.applicationServerKey,applicationServerKey)){await homeService.unsubscribePush(currentSubscription.endpoint);await currentSubscription.unsubscribe();}const subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey});await homeService.subscribePush(subscription.toJSON());setSubscribed(true);setMessage('Push-уведомления включены для этого устройства.');}catch(error){setMessage(error instanceof Error?error.message:'Не удалось включить уведомления.');}finally{setBusy(false);}};
  const disable=async()=>{setBusy(true);setMessage('');try{const subscription=await (await navigator.serviceWorker.ready).pushManager.getSubscription();if(subscription){await homeService.unsubscribePush(subscription.endpoint);await subscription.unsubscribe();}setSubscribed(false);setMessage('Push-уведомления отключены на этом устройстве.');}catch(error){setMessage(error instanceof Error?error.message:'Не удалось отключить уведомления.');}finally{setBusy(false);}};
  return <div className="settings-card"><h3>Уведомления</h3><p>{subscribed?'Push включены для этого устройства.':'Получайте новые приглашения и детали свиданий, даже когда приложение закрыто.'}</p>{configured===false&&<p className="push-hint">Сервер ещё не настроен: добавьте VAPID-ключи в `.env` и перезапустите приложение.</p>}{!supported&&<p className="push-hint">Откройте установленное приложение по HTTPS, чтобы включить Push.</p>}<button className="soft-button" disabled={busy||configured===null} onClick={subscribed?disable:enable}>{busy?'Подождите…':subscribed?'Отключить Push':'Включить Push'}</button>{message&&<p className="reset-message">{message}</p>}</div>;
}

function DateTypeSettings() {
  const space=useRxBind(homeService.space$); const session=useRxBind(homeService.session$); const [title,setTitle]=useState(''); const [emoji,setEmoji]=useState('✨'); const [swipedTypeId,setSwipedTypeId]=useState<string|null>(null); const touchStartX=useRef<number|null>(null); const admin=space?.members.some(member=>member.id===session?.user.id&&member.role==='admin');
  if(!space)return null;
  const add=async(event:FormEvent)=>{event.preventDefault();if(title.trim()){await homeService.addType(title,emoji);setTitle('');}};
  const remove=async(typeId:string)=>{await homeService.deleteType(typeId);setSwipedTypeId(null);};
  return <div className="settings-card"><h3>Ваши правила для свиданий</h3><p>Свайпните тип влево, чтобы удалить его из пространства. Прошлые свидания сохранятся.</p><div className="type-list">{space.dateTypes.map(type=><div key={type.id} className={'type-swipe '+(swipedTypeId===type.id?'revealed':'')} onTouchStart={event=>{touchStartX.current=event.touches[0]?.clientX??null;}} onTouchEnd={event=>{const endX=event.changedTouches[0]?.clientX; if(touchStartX.current!==null&&endX!==undefined&&touchStartX.current-endX>50)setSwipedTypeId(type.id); touchStartX.current=null;}}>{admin&&<button className="type-delete" type="button" aria-label={`Удалить тип «${type.title}»`} onClick={()=>void remove(type.id)}>Удалить</button>}<label className="type-toggle"><span>{type.emoji} {type.title}</span><input disabled={!admin} type="checkbox" checked={type.enabled} onChange={e=>homeService.setType(type.id,e.target.checked)}/></label></div>)}</div>{admin&&<form className="add-type" onSubmit={add}><input value={emoji} onChange={e=>setEmoji(e.target.value)} maxLength={4}/><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Новый тип свидания"/><button>Добавить</button></form>}</div>;
}

export default function App() {
  const session=useRxBind(homeService.session$); const space=useRxBind(homeService.space$); const dates=useRxBind(homeService.dates$); const [tab,setTab]=useState<'plan'|'ideas'|'history'|'space'>('plan'); const [creating,setCreating]=useState(false); const [organizingIdea,setOrganizingIdea]=useState<DateItem|null>(null); const [selectedDateId,setSelectedDateId]=useState(()=>new URLSearchParams(location.search).get('date')); const params=new URLSearchParams(location.search); const inviteToken=params.get('invite'); const resetToken=params.get('reset'); const verifyToken=params.get('verify');
  useEffect(()=>{if(!session?.token)return;void homeService.refresh();const timer=window.setInterval(()=>void homeService.refresh(),30000);return()=>window.clearInterval(timer);},[session]);
  if(!session?.token)return verifyToken?<EmailVerification token={verifyToken}/>:resetToken?<PasswordReset token={resetToken}/>:params.has('forgot')?<PasswordReset/>:inviteToken?<AcceptInvite invite={inviteToken}/>:<Auth/>;
  const ideas=dates.filter(item=>item.status==='planned'&&item.requestedWindow==='idea'); const planned=dates.filter(item=>item.status==='planned'&&item.requestedWindow!=='idea').sort((left,right)=>planDeadline(left)-planDeadline(right)); const completedDates=dates.filter(item=>item.status==='completed');
  const openDate=(dateId:string)=>{const query=new URLSearchParams(location.search);query.set('date',dateId);history.replaceState({},'',`${location.pathname}?${query}`);const item=dates.find(date=>date.id===dateId);setTab(item?.status==='completed'?'history':item?.requestedWindow==='idea'?'ideas':'plan');setSelectedDateId(dateId);}; const closeDetails=()=>{const query=new URLSearchParams(location.search);query.delete('date');history.replaceState({},'',query.size?`${location.pathname}?${query}`:location.pathname);setSelectedDateId(null);}; const selectedDate=dates.find(item=>item.id===selectedDateId)??null;
  return <main className="app"><header><div><p className="eyebrow">НАШЕ ПРОСТРАНСТВО</p><h1>{space?.name??'Загрузка…'} <span>♥</span></h1></div><div className="header-actions"><Notifications openDate={openDate}/><ProfileMenu name={session.user.name} email={session.user.email}/></div></header><section className="hero"><div><p>Следующее тёплое воспоминание</p><h2>{planned[0]?.title??'Давайте придумаем что-то хорошее'}</h2><span>{planned[0]?dateTiming(planned[0]):'Не обязательно ждать повода'}</span></div><button className="new-date" onClick={()=>setCreating(true)}>+ Позвать на свидание</button></section><nav>{([['ideas','Банк идей'],['plan','Планы'],['history','Воспоминания'],['space','Мы']]as const).map(([id,label])=><button key={id} className={tab===id?'active':''} onClick={()=>setTab(id)}>{label}</button>)}</nav>{tab==='plan'&&<section className="content"><div className="section-title"><h2>Впереди</h2><span>{planned.length?'Есть что ждать':'Пока тихо'}</span></div>{planned.length?<div className="grid">{planned.map(item=><DateCard key={item.id} item={item} openDetails={openDate}/>)}</div>:<div className="empty">Ваш календарь ещё чист. Отправьте первое приглашение.</div>}</section>}{tab==='ideas'&&<section className="content"><div className="section-title"><h2>Банк идей</h2><span>{ideas.length?'Без срока, но с настроением':'Пока пусто'}</span></div>{ideas.length?<div className="grid">{ideas.map(item=><DateCard key={item.id} item={item} idea openDetails={openDate} organiseIdea={setOrganizingIdea}/>)}</div>:<div className="empty">Здесь будут свидания без даты, к которым можно вернуться, когда появится настроение.</div>}</section>}{tab==='history'&&<section className="content"><div className="section-title"><h2>Ваши свидания</h2></div>{completedDates.length?<div className="grid">{completedDates.map(item=><DateCard key={item.id} item={item} history openDetails={openDate}/>)}</div>:<div className="empty">Здесь будут ваши тёплые воспоминания и фотографии.</div>}</section>}{tab==='space'&&<section className="content settings"><h2>Наше пространство</h2><InstallApp/><PushSettings/><InvitePartner/><DateTypeSettings/><div className="settings-card"><h3>Вы вдвоём</h3>{space?.members.map(member=><p key={member.id}><b>{member.name}</b> · {member.role==='admin'?'администратор':'участник'}</p>)}</div></section>}{selectedDate&&<DateDetailsDialog item={selectedDate} close={closeDetails}/>} {creating&&<CreateDate close={()=>setCreating(false)}/>} {organizingIdea&&<ClaimIdeaDialog item={organizingIdea} close={()=>setOrganizingIdea(null)}/>}</main>;
}
